# Generated by Django 5.0.6 on 2024-05-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quality',
            new_name='quanlity',
        ),
    ]
