# Generated by Django 5.0.6 on 2024-05-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerceapp', '0002_rename_quality_product_quanlity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
